# crds:
#   annotations:
#      "helm.sh/hook": pre-install, pre-upgrade
# extraObjects:
#   - apiVersion: argoproj.io/v1alpha1
#     kind: Application
#     metadata:
#       name: app-of-apps
#       namespace: argocd
#       finalizers:
#       - resources-finalizer.argocd.argoproj.io
#     spec:
#       project: default
      
#       source:
#         repoURL: 'https://github.com/KleinTova/portfolio-gitops-config.git'
#         targetRevision: main
#         path: apps

#       destination:
#         server: 'https://kubernetes.default.svc'
#         namespace: default

#       syncPolicy:
#         automated:
#           prune: true
#           selfHeal: true

applications:
  root:
    namespace: argocd
    additionalLabels: {}
    additionalAnnotations: {}
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: default
    sources:
    - repoURL: 'https://github.com/KleinTova/portfolio-gitops-config.git'
      path: apps
      targetRevision: main
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: true
        selfHeal: true