# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "tova-portfolio-terraform-bucket"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "us-east-1"
  }
}
